# Generated by Django 4.2.6 on 2023-10-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='path_photo',
        ),
        migrations.AddField(
            model_name='moment',
            name='photo_path',
            field=models.CharField(max_length=300, null=True, verbose_name='Путь до фото'),
        ),
    ]
