# Generated by Django 4.2.6 on 2023-10-25 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moment', '0002_remove_moment_path_photo_moment_photo_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('moment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moment.moment')),
            ],
        ),
    ]
