# Generated by Django 4.2.7 on 2023-11-13 13:37

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_to),
        ),
    ]
