# Generated by Django 4.2.7 on 2023-11-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_moment_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='photo_path',
        ),
    ]
