# Generated by Django 4.2.7 on 2023-11-14 17:02

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_moment_photo_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_to),
        ),
    ]
