# Generated by Django 4.2.6 on 2023-10-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registration', models.DateTimeField(auto_created=True, verbose_name='Дата регистрации')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта')),
                ('username', models.CharField(max_length=50, verbose_name='Никнейм')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('photo', models.FilePathField(verbose_name='Путь до фото')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Рейтинг')),
            ],
        ),
    ]
