# Generated by Django 4.2.6 on 2023-10-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_path',
            field=models.CharField(max_length=300, null=True, verbose_name='Путь до фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Рейтинг'),
        ),
    ]
